---
title: "Datos de Delitos en los cantones de Costa Rica - flexdashboard- Marco Melendez Garcia, Canet: B84781"
output: 
  flexdashboard::flex_dashboard:
    theme: sandstone
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r paquetes}
# Carga de paquetes
library(sf)
library(DT)
library(stringi)
library(dplyr)
library(ggplot2)
library(plotly)
library(leaflet)
library(readxl)
```

```{r datos-cantones, message=FALSE, warning=FALSE}
cantones <-
  st_read(dsn = "cantones_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```

```{r datos-delitos, message=FALSE, warning=FALSE}
estadisticas <- read_xls(path="estadisticaspoliciales2021.xls")
estadisticas=subset(estadisticas, select=c("Delito", "Fecha", "Victima", "Edad", "Genero", "Provincia", "Canton"))
```

Mapa
========================================================================================

Column {data-width=500}
-----------------------------------------------------------------------


**Curso: Procesamiento de datos geográficos**   
Profesor: Manuel Vargas del Valle  
Estudiantes: Marco Melendez Garcia, Carnet: B84781  
Año: 2022  
Fuente: [Instituto Geográfico Nacional (IGN)](https://www.snitcr.go.cr/ign_ign) y [Organismo de Investigación Judicial (OIJ)](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos)  

```{r, message=FALSE, warning=FALSE}
cantones <-
  cantones %>%
  mutate(canton_normalizado = tolower(stri_trans_general(canton, id = "Latin-ASCII")))
estadisticas <-
  estadisticas %>%
  mutate(Canton = if_else(Canton == "LEON CORTES", "LEON CORTES CASTRO", Canton)) %>%
  mutate(Canton = if_else(Canton == "VASQUEZ DE CORONADO", "VAZQUEZ DE CORONADO", Canton))
estadisticas <-
  estadisticas %>%
  mutate(canton_normalizado = tolower(stri_trans_general(Canton, id = "Latin-ASCII")))
```

```{r, message=FALSE, warning=FALSE}
estadisticas <-
  estadisticas %>%
  left_join(
    dplyr::select(
      st_drop_geometry(cantones),
      cod_canton,
      canton_normalizado
    ),
    by = "canton_normalizado",
    copy = FALSE,
    keep = FALSE
  )
```

```{r, message=FALSE, warning=FALSE}
delitos_x_canton <-
  estadisticas %>%
  count(cod_canton, name = "estadisticas")
cantones_delitos <-
  cantones %>%
  left_join(
    delitos_x_canton,
    by = "cod_canton",
    copy = FALSE,
    keep = FALSE
  )
```

```{r, paleta_color, message=FALSE, warning=FALSE}
colores_delitos <-
  colorNumeric(palette = "plasma",
               domain = cantones_delitos$delitos,
               na.color = "transparent")
```

```{r, mapa_coropletas, message=FALSE, warning=FALSE}
leaflet() %>%
  setView(
    lng = -84.19452,
    lat = 9.572735,
    zoom = 7) %>%
  addTiles(group = "OpenStreetMap") %>% 
  addPolygons(
    data = cantones_delitos,
    fillColor = ~ colores_delitos(cantones_delitos$estadisticas),
    fillOpacity = 0.8,
    color = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      paste(
        "<strong>Cantón:</strong>",
        cantones_delitos$canton
      ),
      paste(
        "<strong>Delitos:</strong>",
        cantones_delitos$estadisticas
      ),
      sep = '<br/>'
    ),
    group = "Delitos en cantones"
  ) %>%
  addLayersControl(
    # control de capas
    baseGroups = c("OpenStreetMap"),
    overlayGroups = c("Delitos en cantones")
  ) %>%
  addLegend(
    # leyenda
    position = "bottomleft",
    pal = colores_delitos,
    values = cantones_delitos$estadisticas,
    group = "Delitos",
    title = "Cantidad de delitos"
  )
```


Column {data-width=500}
----------------------------------------------------------------------


### Tabla

```{r, message=FALSE, warning=FALSE}
estadisticas %>%
  dplyr::select(Delito,Fecha,
                Victima, 
                Edad, 
                Genero, 
                Provincia, 
                Canton,
                ) %>%
  datatable(
    options = list(
      pageLength = 20,
     Language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    ),
    colnames = c(
      "Delito",
      "Fecha",
      "Víctima",
      "Edad",
      "Género",
      "Provincia",
      "Cantón"
    )
  )
```

Gráficos
=======================================================================

Column {data-width=250}
-----------------------------------------------------------------------

### Gráfico por tipo de delito

```{r grafico}
grafico_por_tipo_de_delito <-
  estadisticas %>%
  count(Delito) %>%
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity",fill = "red") +
  ggtitle("Delitos por tipo ") +
  xlab("Tipo de delito") +
  ylab("Cantidad") +
  coord_flip() +
  theme_minimal()
ggplotly(grafico_por_tipo_de_delito)
```


### Gráficos de delitos por mes

```{r Delitos_por_mes}
estadisticas <-
estadisticas %>%
mutate(fecha = lubridate::month(Fecha))
mes <-c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre")
```
```{r}
Delitos_por_mes <-
  estadisticas%>%
  count(fecha) %>%
  ggplot(level =level_order,(aes(x = reorder(mes, fecha), y = n)))  +
  geom_bar(stat = "identity", fill = "blue") +
  ggtitle("Delitos durante el año 2021") +
  xlab("Mes") +
  ylab("Cantidad de delitos") +
  theme_minimal()
ggplotly(Delitos_por_mes)
```


Column {data-width=250}
-----------------------------------------------------------------------

### Gráfico de delitos por género

```{r Delitos por género}
delitos_por_genero <-
  estadisticas %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill") +
  ggtitle("Delito por género") +
  xlab("Delito") +
  ylab("Cantidad") +
  labs(fill = "Género") +
  coord_flip() +
  theme_minimal()+
  scale_fill_manual(values = c("#0F0F0F", "#4209ED", "#FF0A6CB3"))
ggplotly(delitos_por_genero) %>% config(locale = 'es')
```



### Gráfico delitos por víctima

```{r,Gráfico_delitos_por_víctima}
tabla4=summarise(group_by(estadisticas, Victima),
                n=n())
ggplot2_cantidad_delvic <- 
  ggplot(tabla4,aes(y=reorder(Victima,+n), x=n)) +
  geom_bar(stat = "identity", fill=c("red")) +
  ylab("Tipo de víctima") +
  xlab("Cantidad de delitos") +
  theme_classic()
ggplotly(ggplot2_cantidad_delvic) %>% config(locale = 'es')
```